language: r

script:
  - bash build.sh

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e "covr::coveralls(type='all')"
