library(testthat)
m.inc <- new(penmap::penmap)
test_that("one insert one row 0.1", {
  m.inc$insert(0.1, 2.0, 3)
  (df <- m.inc$df())
  expect_equal(df, data.frame(penalty=0.1, loss_on=2, size_on=3, loss_after=Inf, size_after=-1))
})
test_that("two inserts, same size, two rows", {
  m.inc$insert(0.2, 2.0, 3)
  (df <- m.inc$df())
  expect_equal(df, data.frame(penalty=c(0.1, 0.2), loss_on=2, size_on=3, loss_after=c(2,Inf), size_after=c(3,-1)))
})
test_that("three inserts, same size, two rows", {
  m.inc$insert(0.3, 2.0, 3)
  (df <- m.inc$df())
  expect_equal(df, data.frame(penalty=c(0.1, 0.3), loss_on=2, size_on=3, loss_after=c(2,Inf), size_after=c(3,-1)))
})

m.dec <- new(penmap::penmap)
test_that("one insert one row 0.3", {
  m.dec$insert(0.3, 2.0, 3)
  (df <- m.dec$df())
  expect_equal(df, data.frame(penalty=0.3, loss_on=2, size_on=3, loss_after=Inf, size_after=-1))
})
test_that("two inserts, same size, two rows, dec", {
  m.dec$insert(0.2, 2.0, 3)
  (df <- m.dec$df())
  expect_equal(df, data.frame(penalty=c(0.2, 0.3), loss_on=2, size_on=3, loss_after=c(2,Inf), size_after=c(3,-1)))
})
test_that("three inserts, same size, two rows, dec", {
  m.dec$insert(0.1, 2.0, 3)
  (df <- m.dec$df())
  expect_equal(df, data.frame(penalty=c(0.1, 0.3), loss_on=2, size_on=3, loss_after=c(2,Inf), size_after=c(3,-1)))
})

m.points <- new(penmap::penmap)
test_that("one insert one row 0.1 30", {
  m.points$insert(0.1, 2.0, 30)
  (df <- m.points$df())
  expect_equal(df, data.frame(penalty=0.1, loss_on=2, size_on=30, loss_after=Inf, size_after=-1))
})
test_that("two inserts, two rows, 30 20", {
  m.points$insert(0.2, 3.5, 20)
  (df <- m.points$df())
  expect_equal(df, data.frame(penalty=c(0.1, 0.2), loss_on=c(2.0, 3.5), size_on=c(30, 20), loss_after=Inf, size_after=-1))
})
test_that("three inserts, three rows, 30 20 10", {
  m.points$insert(0.3, 6.5, 10)
  (df <- m.points$df())
  expect_equal(df, data.frame(penalty=c(0.1, 0.2, 0.3), loss_on=c(2.0, 3.5, 6.5), size_on=c(30, 20, 10), loss_after=Inf, size_after=-1))
})

test_that("error already known", {
  m.dup <- new(penmap::penmap)
  m.dup$insert(0.1, 2.0, 3)
  expect_error({
    m.dup$insert(0.1, 2.0, 3)
  }, class="std::range_error")
  m.dup$insert(0.5, 2.0, 3)
  expect_error({
    m.dup$insert(0.1, 2.0, 3)
  }, class="std::range_error")
  expect_error({
    m.dup$insert(0.2, 2.0, 3)
  }, class="std::range_error")
  expect_error({
    m.dup$insert(0.5, 2.0, 3)
  }, class="std::range_error")
})

test_that("breakpoint and model size ok", {
  m <- new(penmap::penmap)
  m$insert(1.0, 2.0, 3)
  expect_equal(m$df(), data.frame(penalty=1.0, loss_on=2.0, size_on=3, loss_after=Inf, size_after=-1))
  m$insert(2.0, 3.5, 2)
  (res <- m$df())
  expect_equal(res, data.frame(penalty=c(1.0, 1.5, 2.0), loss_on=c(2.0, 2.0, 3.5), size_on=c(3, 3, 2), loss_after=c(2, 3.5, Inf), size_after=c(3, 2, -1)))
})

test_that("insert three models ok with cross point size=2", {
  m=new(penmap::penmap)
  m$insert(2, 3.5, 2)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=2, loss_on=3.5, size_on=2, loss_after=Inf, size_after=-1))
  ## at penalty=3 size_on=1 and 2 are optimal
  m$insert(3, 3.5, 2)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2,3), loss_on=3.5, size_on=2, loss_after=c(3.5, Inf), size_after=c(2, -1)))
  m$insert(4, 10, 0)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2,3,4), loss_on=c(3.5,3.5,10), size_on=c(2,2,0), loss_after=c(3.5,Inf,Inf), size_after=c(2,-1,-1)))
  m$insert(3.1, 6.5, 1)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2,3,3.5,4), loss_on=c(3.5,3.5,6.5,10), size_on=c(2,2,1,0), loss_after=c(3.5,6.5,10,Inf), size_after=c(2,1,0,-1)))
})

test_that("insert three models ok with cross point size=1", {
  m=new(penmap::penmap)
  m$insert(2, 3.5, 2)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=2, loss_on=3.5, size_on=2, loss_after=Inf, size_after=-1))
  ## at penalty=3 size_on=1 and 2 are optimal
  m$insert(3, 6.5, 1)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2,3), loss_on=c(3.5, 6.5), size_on=c(2,1), loss_after=c(3.5,Inf), size_after=c(2,-1)))
  m$insert(4, 10, 0)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2,3,3.5,4), loss_on=c(3.5,6.5,6.5,10), size_on=c(2,1,1,0), loss_after=c(3.5,6.5,10,Inf), size_after=c(2,1,0,-1)))
})

test_that("insert three models ok with cross point size=1 other side", {
  m=new(penmap::penmap)
  m$insert(3, 6.5, 1)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=3, loss_on=6.5, size_on=1, loss_after=Inf, size_after=-1))
  m$insert(2, 3.5, 2)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2,3), loss_on=c(3.5, 6.5), size_on=c(2,1), loss_after=c(3.5,Inf), size_after=c(2,-1)))
  m$insert(4, 10, 0)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2,3,3.5,4), loss_on=c(3.5,6.5,6.5,10), size_on=c(2,1,1,0), loss_after=c(3.5,6.5,10,Inf), size_after=c(2,1,0,-1)))
})

test_that("insert three models ok with fill larger smaller", {
  m=new(penmap::penmap)
  m$insert(2, 3.5, 2)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=2, loss_on=3.5, size_on=2, loss_after=Inf, size_after=-1))
  m$insert(4, 10, 0)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2, 4), loss_on=c(3.5, 10), size_on=c(2, 0), loss_after=Inf, size_after=-1))
  m$insert(3.25, 6.5, 1)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(2, 3, 3.5, 4), loss_on=c(3.5, 3.5, 6.5, 10), size_on=c(2, 2, 1, 0), loss_after=c(3.5,6.5,10,Inf), size_after=c(2,1,0,-1)))
})

test_that("breakpoints are combined", {
  m = new(penmap::penmap)
  m$insert(0, 2, 3)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=0, loss_on=2, size_on=3, loss_after=Inf, size_after=-1))
  m$insert(2, 3.5, 2)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(0,1.5,2), loss_on=c(2,2,3.5), size_on=c(3,3,2), loss_after=c(2,3.5,Inf), size_after=c(3,2,-1)))
  m$insert(5, 10, 0)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(0,1.5,2,5), loss_on=c(2,2,3.5,10), size_on=c(3,3,2,0), loss_after=c(2,3.5,Inf,Inf), size_after=c(3,2,-1,-1)))
  m$insert(3.25, 10, 0)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(0,1.5,3.25,5), loss_on=c(2,2,3.5,10), size_on=c(3,3,2,0), loss_after=c(2,3.5,10,Inf), size_after=c(3,2,0,-1)))
})

## test_that("inserted penalty = larger intersect ok Inf", {
##   m = new(penmap::penmap)
##   m$insert(0, 2, 3)
##   expect_equal(m$df(), data.frame(penalty=0, loss_on=2, size_on=3, loss_after=Inf, size_after=-1))
##   m$insert(Inf, 10, 0)
##   expect_equal(m$df(), data.frame(penalty=c(0, Inf), loss_on=c(2,10), size_on=c(3,0), loss_after=Inf, size_after=-1))
##   m$insert(3.5, 6.5, 1)
##   expect_equal(m$df(), data.frame(penalty=c(0, 3.5), loss_on=c(2,6.5), size_on=c(3,1), loss_after=c(Inf, 10), size_after=c(-1, 0)))
##   m$insert(2, 3.5, 2)
##   expect_equal(m$df(), data.frame(penalty=c(0, 1.5, 3, 3.5), loss_on=c(2, 3.5, 6.5, 10), size_on=c(3,2,1,0), loss_after=c(2,3.5,6.5,10), size_after=c(3,2,1,0)))
## })

## test_that("inserted penalty = larger intersect ok finite", {
##   m = new(penmap::penmap)
##   m$insert(0, 2, 103)
##   (df <- m$df())
##   expect_equal(df, data.frame(penalty=0, loss_on=2, size_on=103, loss_after=Inf, size_after=-1))
##   m$insert(8, 10, 100)
##   (df <- m$df())
##   expect_equal(df, data.frame(penalty=c(0, 8), loss_on=c(2,10), size_on=c(103,100), loss_after=Inf, size_after=-1))
##   m$insert(3.5, 6.5, 101)
##   (df <- m$df())
##   expect_equal(df, data.frame(penalty=c(0, 3.5), loss_on=c(2,6.5), size_on=c(103,101), loss_after=c(Inf, 10), size_after=c(-1, 100)))
##   m$insert(2, 3.5, 102)
##   (df <- m$df())
##   expect_equal(df, data.frame(penalty=c(0, 1.5, 3, 3.5), loss_on=c(2, 3.5, 6.5, 10), size_on=c(103,102,101,100), loss_after=c(2,3.5,6.5,10), size_after=c(103,102,101,100)))
## })

test_that("inserted penalty = larger intersect ok finite interval", {
  m = new(penmap::penmap)
  m$insert(0, 2, 103)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=0, loss_on=2, size_on=103, loss_after=Inf, size_after=-1))
  m$insert(8, 10, 100)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(0, 8), loss_on=c(2,10), size_on=c(103,100), loss_after=Inf, size_after=-1))
  m$insert(9, 10, 100)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(0,8,9), loss_on=c(2,10,10), size_on=c(103,100,100), loss_after=c(Inf,10,Inf), size_after=c(-1,100,-1)))
  m$insert(3.5, 6.5, 101)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(0,3.5,9), loss_on=c(2,6.5,10), size_on=c(103,101,100), loss_after=c(Inf,10,Inf), size_after=c(-1, 100,-1)))
  m$insert(2, 3.5, 102)
  (df <- m$df())
  expect_equal(df, data.frame(penalty=c(0, 1.5, 3, 3.5, 9), loss_on=c(2, 2, 3.5, 6.5, 10), size_on=c(103,103,102,101,100), loss_after=c(2,3.5,6.5,10,Inf), size_after=c(103,102,101,100,-1)))
})
